export const contractAddress = "0xef85fe40f25bf8ad9d4c43968c3592997df22e5b";
export const abi = [
  {
    type: "constructor",
    inputs: [
      { name: "locker_", type: "address", internalType: "address" },
      { name: "uniswapV3Factory_", type: "address", internalType: "address" },
      { name: "positionManager_", type: "address", internalType: "address" },
      { name: "swapRouter_", type: "address", internalType: "address" },
      { name: "owner_", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "admins",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "allowedPairedTokens",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approveToken",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimRewards",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deployToken",
    inputs: [
      { name: "_name", type: "string", internalType: "string" },
      { name: "_symbol", type: "string", internalType: "string" },
      { name: "_supply", type: "uint256", internalType: "uint256" },
      { name: "_fee", type: "uint24", internalType: "uint24" },
      { name: "_salt", type: "bytes32", internalType: "bytes32" },
      { name: "_deployer", type: "address", internalType: "address" },
      { name: "_fid", type: "uint256", internalType: "uint256" },
      { name: "_image", type: "string", internalType: "string" },
      { name: "_castHash", type: "string", internalType: "string" },
      {
        name: "_poolConfig",
        type: "tuple",
        internalType: "struct Clanker.PoolConfig",
        components: [
          { name: "tick", type: "int24", internalType: "int24" },
          { name: "pairedToken", type: "address", internalType: "address" },
          { name: "devBuyFee", type: "uint24", internalType: "uint24" },
        ],
      },
      { name: "earthAmount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "token", type: "address", internalType: "contract ClankerToken" },
      { name: "positionId", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deploymentInfoForToken",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "positionId", type: "uint256", internalType: "uint256" },
      { name: "locker", type: "address", internalType: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "deprecated",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "earth",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "liquidityLocker",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract LpLockerv2" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "positionManager",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract INonfungiblePositionManager" }],
    stateMutability: "view",
  },
  { type: "function", name: "renounceOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "setAdmin",
    inputs: [
      { name: "admin", type: "address", internalType: "address" },
      { name: "isAdmin", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setDeprecated",
    inputs: [{ name: "_deprecated", type: "bool", internalType: "bool" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "swapExactInputSingle",
    inputs: [
      { name: "tokenIn", type: "address", internalType: "address" },
      { name: "tokenOut", type: "address", internalType: "address" },
      { name: "fee", type: "uint24", internalType: "uint24" },
      { name: "recipient", type: "address", internalType: "address" },
      { name: "deadline", type: "uint256", internalType: "uint256" },
      { name: "amountIn", type: "uint256", internalType: "uint256" },
      { name: "amountOutMinimum", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "amountOut", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "swapRouter",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract ISwapRouter" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "toggleAllowedPairedToken",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "allowed", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "tokensDeployedByUsers",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "positionId", type: "uint256", internalType: "uint256" },
      { name: "locker", type: "address", internalType: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "uniswapV3Factory",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IUniswapV3Factory" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "updateLiquidityLocker",
    inputs: [{ name: "newLocker", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "version",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AdminUpdated",
    inputs: [
      { name: "admin", type: "address", indexed: false, internalType: "address" },
      { name: "status", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DeprecatedStatusUpdated",
    inputs: [{ name: "status", type: "bool", indexed: false, internalType: "bool" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "LockerUpdated",
    inputs: [{ name: "newLocker", type: "address", indexed: false, internalType: "address" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      { name: "previousOwner", type: "address", indexed: true, internalType: "address" },
      { name: "newOwner", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PairedTokenUpdated",
    inputs: [
      { name: "token", type: "address", indexed: false, internalType: "address" },
      { name: "allowed", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RewardsClaimed",
    inputs: [
      { name: "token", type: "address", indexed: false, internalType: "address" },
      { name: "positionId", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "recipient", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SwapExecuted",
    inputs: [
      { name: "tokenIn", type: "address", indexed: false, internalType: "address" },
      { name: "tokenOut", type: "address", indexed: false, internalType: "address" },
      { name: "amountIn", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "amountOut", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TokenCreated",
    inputs: [
      { name: "tokenAddress", type: "address", indexed: false, internalType: "address" },
      { name: "positionId", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "deployer", type: "address", indexed: false, internalType: "address" },
      { name: "fid", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "name", type: "string", indexed: false, internalType: "string" },
      { name: "symbol", type: "string", indexed: false, internalType: "string" },
      { name: "supply", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "lockerAddress", type: "address", indexed: false, internalType: "address" },
      { name: "castHash", type: "string", indexed: false, internalType: "string" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TokensSplit",
    inputs: [
      { name: "token", type: "address", indexed: false, internalType: "address" },
      { name: "deployer", type: "address", indexed: false, internalType: "address" },
      { name: "deployerAmount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "poolAmount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  { type: "error", name: "Deprecated", inputs: [] },
  { type: "error", name: "ExpiredDeadline", inputs: [] },
  { type: "error", name: "InsufficientEARTH", inputs: [] },
  { type: "error", name: "InsufficientLiquidity", inputs: [] },
  { type: "error", name: "InvalidConfig", inputs: [] },
  { type: "error", name: "InvalidFee", inputs: [] },
  { type: "error", name: "InvalidTickSpacing", inputs: [] },
  { type: "error", name: "NotAdmin", inputs: [{ name: "user", type: "address", internalType: "address" }] },
  {
    type: "error",
    name: "NotAllowedPairedToken",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
  { type: "error", name: "OwnableInvalidOwner", inputs: [{ name: "owner", type: "address", internalType: "address" }] },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "PoolCreationFailed", inputs: [] },
  { type: "error", name: "SwapFailed", inputs: [] },
  { type: "error", name: "TokenNotFound", inputs: [{ name: "token", type: "address", internalType: "address" }] },
  { type: "error", name: "TransferFailed", inputs: [] },
  { type: "error", name: "ZeroMinimumOutput", inputs: [] },
];
