import {Source_Code_Pro,Courier_Prime } from "next/font/google";
import "./globals.css";

const sourceCodePro = Source_Code_Pro({
  variable: "--primary-font",
  subsets: ["latin"],
  weight: ['200' , '300' , '400' , '500' , '600' , '700' , '800' , '900']
});

const courierPrime = Courier_Prime({
  variable: "--secondary-font",
  subsets: ["latin"],
  weight: ['400','700']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sourceCodePro.variable} ${courierPrime.variable} antialiased`}
      >
        {children}
       
      </body>
    </html>
  );
}
